# Generated by Django 2.1.4 on 2019-04-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admno', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('std', models.CharField(choices=[('A', 'I'), ('B', 'II'), ('C', 'III'), ('D', 'IV')], max_length=1)),
                ('section', models.CharField(max_length=15)),
                ('active', models.BooleanField()),
            ],
            options={
                'verbose_name': 'candidate',
                'verbose_name_plural': 'candidates',
                'ordering': ['admno'],
            },
        ),
    ]
